const TestError = () => {
  throw new Error("Test error boundary functionality");
};

export default TestError;
